### ISSUE TITLE
OmegaConfigLoader requires consistent config for each env

### ISSUE THREAD

**Issue by KrzysztofDobosz** [kedro-org/kedro#2704] opened 2023-06-20 14:34 UTC
## Description
OmegaConfigLoader checks for completeness config for each env before updating base config with values from local. This prevents defining global values for data catalog in base config only.

## Context
I was trying to use templating with Omega in v 0.18.10. I have sql queries which form spark.SparkJDBCDataSet in base and pandas.SQLQueryDataSet in local. My goal was to be able to define the query just in one place (conf/base/catalog_globals.yml).

## Steps to Reproduce
1. Define a global value in conf/base/catalog_globals.yml
2. Use this value in dataset in both base and local config envs.

## Expected Result
Config from base is updated with values from local, and then templated values are resolved.

## Actual Result
This exception is thrown, unless I define globals also in local env (which I was trying to avoid).

```
InterpolationKeyError: Interpolation key '***' not found
```

## Your Environment
* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.10
* Python version used (`python -V`): 3.9
* Operating system and version: Windows 10

**Comment by astrojuanlu** [comment] 2023-06-20 14:40
Hi @KrzysztofDobosz, thanks for opening this issue. Could you share a YAML snippet of what do you mean by:

> This prevents defining global values for data catalog in base config only.

**Comment by ankatiyar** [comment] 2023-06-21 14:01
Thanks for reporting this @KrzysztofDobosz! I've been able to reproduce it. Working on a fix.

**Comment by ankatiyar** [comment] 2023-07-03 14:03
Hey @KrzysztofDobosz, turns out this is expected behaviour for now. We're still working on adding globals functionality for `OmegaConfigLoader` https://github.com/kedro-org/kedro/issues/2175. Closing this issue but feel free to the discussion on the globals issue! :)

**Closed by ankatiyar** 2023-07-03 14:03 UTC
Labels: Issue: Bug Report 🐞, Community
