### ISSUE TITLE
Strict linkage between after_dataset_loaded hook to specific pipeline(s)?

### ISSUE THREAD

**Issue by lhegstrom** [kedro-org/kedro#1308] opened 2022-03-02 22:49 UTC
I have a project with multiple files that need to be processed in two different pipelines (Pipe A, Pipe B). The files are fairly different.

For `pipeline A` I have a hook that I'd like to run after the dataset is loaded. 
The hook functionality is to basically add two columns to the dataframe, based on the file name, etc. 

The function I wrote works perfectly for `Pipeline A`. However, `Pipeline B` also calls the hook after loading its dataset.

Looking further down the road, one can imagine a scenario with many nicely differentiated pipelines, but a massively bloated `after_data_loaded` hook that  needs to have logic that determines which pipeline is calling the hook, which can be messy.

Is there any way to link a hook directly to a specific pipeline? Or do all pipelines have to call the specified hooks?

**Comment by datajoely** [comment] 2022-03-03 07:51
Hi @lhegstrom it would be good to understand what you're trying to do here. Typically, we wouldn't encourage you to do data mutation in a hook - this would be something that we manage within the nodes (and by extension pipelines).

What sort of operations are happening in your `after_data_loaded` hook that couldn't be in the `node` itself?

**Comment by lhegstrom** [comment] 2022-03-03 14:43
Hi @datajoely 

The hook basically adds two columns to the data frame: the quarter and year the file was released. This data is not available within the files. Nor is it in a consistent format in the file name. No other data manipulation is taking place at this step - the rest is applied in the nodes.

In a YAML catalog, for `pipeline A`, I am loading csv files, then naming them in a way that links the quarter and year. The dataset name would be something like: `ASDF_apr_2020` while the filepath is something like `"some complicated string with ~!@$! random things nothing helpful.csv"

The hook logic takes the `dataset_name` parameter, .split('_')'s them, then appends `df['quarter'] = split[1]` and df['year'] = split[2]`.

Pipeline B does not have this issue. The files can be manipulated within the nodes in a usual fashion.
But, when Pipeline B runs, it calls the hook above. It's easy enough to label the files, and perform some basic logic with two pipelines: `if dataset_name.split('_')[0] == 'ASDF':` `else: pass`. But, the project may end up have dozens of pipelines, and having a ton of logic in the hooks to link to the correct pipeline can get messy.

I'm wondering if there is some way I can say Pipeline A -> call this hook. Pipeline B -> no need to call a hook?

**Comment by datajoely** [comment] 2022-03-03 14:49
This is an interesting problem - in some ways because Kedro comes from a perspective being super deterministic and reproducible I'm not sure this is possible via hooks.

I wonder if this is a situation where it makes sense to wrap the Kedro pipelines within an orchestrator like Argo and Airflow with a couple of scripts doing the renaming/moving of files outside of Kedro and using the orchestration layer to run the tasks in the right order.

Keen to keep thinking this through with you - but in general, putting this type of conditional execution logic in hooks feels like it may be quite difficult to debug / maintain.

**Comment by lhegstrom** [comment] 2022-03-03 14:52
Or, the logic can be moved into a node if there is some way to access the `dataset_name`?
Right now the nodes are being given the `DataFrame` as an input, but maybe there is something I haven't thought of

**Comment by datajoely** [comment] 2022-03-03 15:19
So by design the nodes don't have awareness of the IO operation, you can sort of introduce this via hooks as you've discovered.

**Comment by MerelTheisenQB** [comment] 2022-04-04 13:13
I'm closing this issue. As @datajoely explained, the nodes don't have awareness of the IO operation, and we're not planning on changing this.

**Closed by MerelTheisenQB** 2022-04-04 13:13 UTC
Labels: Issue: Feature Request, Community, Component: IO
