### ISSUE TITLE
Dataset factory placeholders do not work in nested dataset definitions

### ISSUE THREAD

**Issue by nilsbore** [kedro-org/kedro#3037] opened 2023-09-15 12:40 UTC
## Description

For example, this definition does not work:
```python
"trains.{sheet_name}":
  type: pandas.ExcelDataSet
  filepath: path/to/nonexistant/file.xlsx
  load_args:
    sheet_name: {sheet_name}
```
because `{sheet_name}` is not available in any level deeper than the top-level dataset definition.

## Context
We are using nested datasets frequently (Partitioned etc.) and need this to define our dataset storage locations, among other things.

## Steps to Reproduce
Add the snippet above to your data catalog. Try to read it using
```
catalog.load("trains.fast"`)
```
Because the file does not exist, this will raise the error:
```
DatasetError: Failed while loading data from data set ExcelDataSet(filepath=path/to/nonexistant/file.xlsx, load_args={'engine': openpyxl, 'sheet_name': {}}, protocol=file, save_args={'index': False}, writer_args={'engine': openpyxl}).
[Errno 2] No such file or directory: 'path/to/nonexistant/file.xlsx'
```
Note that `'sheet_name': {}`. Now replace the dataset definition with:
```python
"trains.{sheet_name}":
  type: pandas.ExcelDataSet
  filepath: path/to/nonexistant/file.xlsx
  load_args:
    sheet_name: slow
```
When loading using the same command, this will raise the error:
```
DatasetError: Failed while loading data from data set ExcelDataSet(filepath=path/to/nonexistant/file.xlsx, load_args={'engine': openpyxl, 'sheet_name': slow}, protocol=file, save_args={'index': False}, writer_args={'engine': openpyxl}).
[Errno 2] No such file or directory: 'path/to/nonexistant/file.xlsx'
```
Note that now `'sheet_name': slow`!

## Expected Result
`sheet_name` should be set to "fast" in the first case.

## Actual Result
`sheet_name` is set to `{}` because placeholders in deeper levels are not correctly resolved when using dataset factories.

## Your Environment

* kedro, version 0.18.13
* Python 3.10.12
* Ubuntu 22.04

**Comment by noklam** [comment] 2023-09-15 13:51
thanks for the report, this is duplicate of https://github.com/kedro-org/kedro/issues/2992

This will be included in the next release, if you are ambitous you can install from source with the `main` branch to try out the fix.

**Closed** 2023-09-15 13:52 UTC
