### ISSUE TITLE
Modular pipelines in parallel with Spark streaming

### ISSUE THREAD

**Issue by asksonu** [kedro-org/kedro#1530] opened 2022-05-15 13:37 UTC
## Description
I am try to reuse modular pipelines and wanted to run them in parallel. This modular pipeline has same functionality but have all their inputs and outputs different. 

## Context
I tried below steps but only one of the pipeline is executing and it is not consistent i;e; if I execute once first one is executed and next time may be 2nd one is executed. Not sure if I am missing anything here.

## Steps to Reproduce
1. create common pipeline in pipeline.py. Only one pipeline created namely base_pipeline.
     ```
    from kedro.pipeline import Pipeline
    def create_pipeline():
        return Pipeline(
            [
                node(
                    node_func1,
                    "input",
                    "output_node1",
                ),
                node(
                    node_func2,
                    ["output_node1","params:some_params"],
                    ["output"],
                ),
           ]
    ```
2. Reuse above pipeline in pipeline_registry.py by creating two new modular pipelines as below:
    ```
    from kedro.pipeline.modular_pipeline import pipeline as ModularPipeline
    pipe1_pipeline = ModularPipeline(
        base_pipeline.create_pipeline(),
        inputs={"input": "input1"},
        outputs={"output": "output1"},
        parameters={"params:some_params": "params:params1"},
        namespace="pipe1",
    )
    pipe2_pipeline = ModularPipeline(
        base_pipeline.create_pipeline(),
        inputs={"input": "input2"},
        outputs={"output": "output2"},
        parameters={"params:some_params": "params:params2"},
        namespace="pipe2",
    )
    return {
        "__default__": (pipe1_pipeline + pipe2_pipeline),
        "pipe1": pipe1_pipeline,
        "pipe2": pipe2_pipeline,
    }
    ```
4. kedro run

## Expected Result
Both output1 and output2 should be the result of kedro run as default has both pipelines.

## Actual Result
I can see either output1 or output2 but not both.

Please help if I am missing anything here. Thanks.

## Your Environment
Currently running in local environment.

* Kedro version used (`pip show kedro` or `kedro -V`):  kedro==0.17.7
kedro-viz==4.3.1
* Python version used (`python -V`):  3.8.6
* Operating system and version: Ubuntu 21.04

**Comment by noklam** [comment] 2022-05-16 10:37
@asksonu Can you do these and post the screenshot of the resulting pipelines?

```
pip install kedro-viz
kedro viz
```

**Comment by asksonu** [comment] 2022-05-17 18:41
Below is the screenshot of the kedro-viz. FYI: The first node reads data from kafka using spark. If I comment out  pipe1 or pipe2 the other is working. 

![image](https://user-images.githubusercontent.com/36418425/168886496-c872564a-5d35-4871-b2ac-648a4f7b4f62.png)

**Comment by noklam** [comment] 2022-05-17 22:35
@asksonu I actually want to see the output of kedro viz as is, can you just show the pipeline that you intened to run？

**Comment by asksonu** [comment] 2022-05-18 05:26
Below is the code in pipeline_registry and I want `default` pipeline to run `kedro run --env=local`. Please let me know if this information is sufficient. 

```
    kafka_read_pipeline = kafka_read.create_pipeline()
    pipe1 = ModularPipeline(
        kafka_to_db.create_pipeline(),
        inputs={
            "kafka_stream": "df1",
            "agg_rules_df": "agg_rules_df",
        },
        outputs={"stream_data_to_db": "data_to_db1"},
        parameters={"params:agg_cols": "params:agg_cols"},
        namespace="pipe1",
    )
    pipe2 = ModularPipeline(
        pipe=kafka_to_db.create_pipeline(),
        inputs={
            "kafka_stream": "df2",
            "agg_rules_df": "agg_rules_df",
        },
        outputs={"stream_data_to_db": "data_to_db2"},
        parameters={"params:agg_cols": "params:agg_cols"},
        namespace="pipe2",
    )
    return {
        "__default__": (kafka_read_pipeline + pipe1 + pipe2),
        "pipe1": kafka_read_pipeline + pipe1,
        "pipe2": kafka_read_pipeline + pipe2
    }
```

Output from `kedro viz`

![image](https://user-images.githubusercontent.com/36418425/168963453-0f28b392-7ef2-43ef-9ee8-57318f5fa9c1.png)

**Comment by noklam** [comment] 2022-05-19 10:01
The computation graph looks correct to me, except there is a strange `df3` not mentioned anywhere?

> Both output1 and output2 should be the result of kedro run as default has both pipelines.

When you say this do you mean only 1 of the 2 pipelines gets executed?

**Comment by asksonu** [comment] 2022-05-19 14:45
@noklam , yes in the above graph `output1` read as `Data to db1` and `output2` as `Data to db2`. When I execute `kedro run --env=local` either data received in `Pipe1` is written to console or  data from `Pipe2` is written to console but not both.

Ignore df3 which I intend to use if df1 and df2 both are working.

**Comment by noklam** [comment] 2022-05-19 15:52
@asksonu From your `kedro-viz` graph it looks like everything is correct, does the node actually get executed base on the log?

I doubt the issue is in the Kafka node where it only send data to one of the downstream, does `df1` and `df2` both contains data actually?

**Comment by asksonu** [comment] 2022-06-11 09:16
Sorry for late reply. I found the issue was with spark streaming behaviour. Using spark streaming on multiple topics, filter can be applied using `foreachBatch`. So I guess we cannot process the records with multiple nodes as `foreachBatch` cannot return anything.
We can officially close the issue. 
Thanks @noklam for your quick response.

**Comment by noklam** [comment] 2022-06-11 09:19
@asksonu Thank you for coming back to share your finding! I will close this issue now.

**Closed** 2022-06-11 09:18 UTC
Labels: Community
