### ISSUE TITLE
Timing issue with executing the same pipeline with versionned dataset

### ISSUE THREAD

**Issue by AlexandreOuellet** [kedro-org/kedro#2694] opened 2023-06-15 15:47 UTC
## Description
The issue is that the version ID (the timestamp) is generated when a node starts its execution.  This creates timing issue when executing the same pipeline that has a different execution time depending on its parameters

## Context
When running 2 experiment at the same time, I'm having unexpected results : The same dataset is suddenly in use in 2 different pipeline run, even though the generated dataset is random.

## Steps to Reproduce
1. Clone [this reprository](https://github.com/AlexandreOuellet/kedro-versionned-dataset-bug) - `git clone git@github.com:AlexandreOuellet/kedro-versionned-dataset-bug.git`
2. `pip install -r src/requirements.txt`
4. Quickly, you need to :
  4.1 `kedro run --params sleep=100` (this will run for ~100 seconds)
  4.2  Wait for a few seconds to make sure the pipeline is running
  4.3  Run `kedro run --params sleep=1` in a new terminal
5. Let both run finish

## Expected Result
Both executions should have different dataset (as they are generated randomly

## Actual Result
The first pipeline's execution is not using the data it generated.  Instead, it uses the data generated by the 2nd execution.

You will find WARNING log simliar to this
```log
This is strongly  discouraged due to inconsistencies it may cause between 'save' and 'load' operations. Please refrain from setting exact load version for intermediate datasets where possible to avoid this warning. 
```

## Your Environment
Everything to repro this bug is available in [this reprository](https://github.com/AlexandreOuellet/kedro-versionned-dataset-bug).

**Comment by noklam** [comment] 2023-06-16 11:45
I can reproduce this issue. I have updated the description to simplify the steps to reproduce it

**Comment by AlexandreOuellet** [comment] 2023-06-22 17:16
No rush, but any idea on an ETA?

**Comment by astrojuanlu** [comment] 2023-06-22 17:31
Hi @AlexandreOuellet, we're going to assess the complexity and priority of this issue in the middle of next sprint at the latest, in a couple of weeks we'll give an update.

**Comment by AlexandreOuellet** [comment] 2023-08-17 16:01
Any update on this issue?

**Comment by astrojuanlu** [comment] 2023-08-17 17:00
Hi @AlexandreOuellet , the issue is a bit trickier than we expected. We cannot commit to an ETA at this point, but at least we'll try to dig a bit deeper into why this is happening and what can be done about it. If you want to provide any additional information in the meantime, feel welcome to do so.

**Comment by AlexandreOuellet** [comment] 2023-10-10 15:55
Any news on that bug?

**Comment by astrojuanlu** [comment] 2023-10-23 13:44
@AlexandreOuellet thanks for your patience, we discussed a bit about this and we aren't sure we want to support more than 1 concurrent `kedro run`, in fact we should probably "lock" the execution. Could you give more details on how this issue appeared in the first place, and how such a lock would affect you?

**Comment by merelcht** [comment] 2024-03-14 12:37
I'm going to close this issue because this functionality is not something we would change without a proper re-design. Versioning is a priority topic for us and we're capturing ideas for it here https://github.com/kedro-org/kedro/issues/1979.

**Closed by merelcht** 2024-03-14 12:37 UTC
Labels: Issue: Bug Report 🐞, Community
