### ISSUE TITLE
Kedro with Prefect 2.0

### ISSUE THREAD

**Issue by mehrzadai** [kedro-org/kedro#2698] opened 2023-06-17 10:25 UTC
## Description
Would you provide an example of using kedro pipelines in Prefect 2 ? 
## Context
I am able to do it easily with a session in a flow but the problem is logs which will not be available in Prefect's UI.

**Comment by noklam** [comment] 2023-06-17 10:30
We haven't updated our documentation with Prefect 2.0, but this is something on our radarm I don't have a working example here but maybe I can help guide you towards it. Would you be able to share your setup how do you make it work?

If possible can I ask you to join slack.kedro.org? It will be easier to respond there.

**Comment by astrojuanlu** [comment] 2023-06-17 12:23
Duplicate of gh-2431, please upvote that issue and let's continue the conversation there.

**Closed by astrojuanlu** 2023-06-17 12:23 UTC
Labels: Issue: Feature Request

**Comment by mehrzadai** [comment] 2023-06-18 10:19
Hi, actually I configured it out and I think it is useful to share.
It is actually the most ideal integration you can consider in your infra design and it is so easy with prefect 2:-
All pipelines are configured in `kedro` and running in prefect with just an easy session request.
all I had to configure was to read logs in prefect UI.
I have configured the logging.yml with a prefect handler :
```
  prefect_api:
      level: 0
      class: prefect.logging.handlers.APILogHandler
  ```
  That is it ! 
  @astrojuanlu :  #2431 will be the place.
