### ISSUE TITLE
High memory usage before the pipeline runs

### ISSUE THREAD

**Issue by FlorianGD** [kedro-org/kedro#3377] opened 2023-12-01 16:07 UTC
## Description

Hi, I have a pipeline that uses a lot of memory. I profiled it with memory_profiler , and there is a huge memory usage, before the first node runs. This is critical for me because I am running it on a kubernetes pods, and if I use too much memory, the pod gets killed. Attached is the profile of a dummy pipeline that I created that prints a parameter and does nothing else. We can see that it uses nearly 200MiB of memory.
I am not sure what I should look for to improve this memory usage. Is it the catalog? If so, how can I reduce it? Is it something else from kedro? Is it outside of kedro?
![memory_profile](https://github.com/kedro-org/kedro/assets/9217921/e66a515d-84d8-4f7f-b91c-bfb5b909e582)

The catalog has some variants of `PartitionedDataset`, `APIDataset`, `PickleDataset` and `CSVDataset`. We have custom datasets (mainly variants of APIDataset with custom payloads, and a variant around the APIDataset, that uses a checkpoint that saves data in a postgresdb table).

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): `0.18.4`
* Python version used (`python -V`): `3.10.10`
* Operating system and version: linux (on code server)

**Comment by noklam** [comment] 2024-01-29 13:08
Thanks for opening this issue. I've tried a few base on what you provided:
I am only running the CLI (not even a particular command, so most likely it is only loading up some modules)
1. ruff (mprof run ruff)
![Image](https://github.com/kedro-org/kedro/assets/18221871/183a857f-d5f9-446e-bdf3-daf0d51696f6)

2. black
![Image](https://github.com/kedro-org/kedro/assets/18221871/920558c7-dba2-4b59-a980-b82d3465caab)
3. kedro (with viz installed)

![Image](https://github.com/kedro-org/kedro/assets/18221871/ceb8f8dc-08e2-4727-b6b0-3f586a7ffda5)
4. kedro (with kedro-viz uninstalled)

![Image](https://github.com/kedro-org/kedro/assets/18221871/6f7d6dc3-7912-4580-9260-5b4c79ccbf13)

#Summary
I believe most of the memory consumption is coming from the libraries import, `kedro viz` tend to have a lot of dependencies, it causes performance issues in the past and we try to mitigate this by hiding the import only when it tries to start a server.

**Comment by noklam** [comment] 2024-03-25 12:54
@FlorianGD While this 200MB is not small, does this cause any problem to you? I intend to close this issue if it's due to libraries import only, unless this is caused by some memory leakage with DataCatalog.

**Comment by noklam** [comment] 2024-03-27 17:31
Closing this after a discussion with @FlorianGD. There is not much Kedro can do to reduce memory footprint from libraries import.

For the context the original issue was on a K8s cluster with several pipeline running in parallel, and was solved by increasing the memory of the cluster.

**Closed by noklam** 2024-03-27 17:31 UTC
