### ISSUE TITLE
Create a manual test procedure for Jupyter Notebook workflows

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro#2137] opened 2022-12-19 14:52 UTC
## Description
Create a checklist for manually testing Jupyter Notebook workflows after making changes to Kedro's `ipython` module that covers common use cases.

## Context

Currently, our unit and end-to-end tests do not cover some common workflows that users have with Jupyter Notebook.

This lets us break these workflows silently, as in https://github.com/kedro-org/kedro/issues/2060.

The core team agreed that end-to-end test cases for these workflows would be too fragile and would add a maintenance burden to our CI that is not justified by the number of changes we tend to make to `ipython`. Therefore, we should create a checklist of manual tests.

**Comment by merelcht** [comment] 2024-03-12 11:27
@noklam @lrcouto @AhdraMeraliQB since you've recently worked on Jupyter functionality, do you think we should still do this ticket?

**Comment by noklam** [comment] 2024-03-12 13:43
@merelcht I read both issues and I don't know what do we need to manually test or why is it not possible to write automated tests?

We have made a lot of improvement to the ipython test suites and I think #3528 is still worth to do but not so urgent. e2e test for Notebook is not possible because it involves frontend logic, it should works for `ipython` at least to make sure the `%load_node` code is not completely broken.

I'd say go ahread and close this issue since we don't have any manual Notebook test since this issue created and it doesn't cause any problem. If there is a specific regression case we can discuss whether we can create automated test for it.

**Closed** 2024-03-14 12:44 UTC
Labels: Component: Testing, Should we delete?
