### ISSUE TITLE
Node caching: avoid unnecessary node execution when inputs, outputs, or logic remain unchanged

### ISSUE THREAD

**Issue by froxec** [kedro-org/kedro#4350] opened 2024-11-24 20:59 UTC
## Description

First of all, thank you for your efforts in developing Kedro.
I believe it would be highly beneficial if Kedro had a built-in node caching feature. By node caching, I mean a mechanism to avoid re-executing a node when its inputs, outputs, and logic remain unchanged.

## Context

This feature is important to me because, in some scenarios, it is necessary to run the entire pipeline multiple times with different configurations. Re-executing nodes that remain unchanged between runs can significantly increase the time required for experiments.

For instance, when tracking pipeline parameters using MLFlow, we need to run the entire pipeline to record parameters for every node. This is because [kedro-mlflow](https://kedro-mlflow.readthedocs.io/en/stable/source/04_experimentation_tracking/02_version_parameters.html#will-parameters-be-recorded-if-the-pipeline-fails-during-execution) records parameters node by node.

## Possible Implementation

There is already an existing plugin, [kedro-cache](https://github.com/AnH0ang/kedro-cache), that implements similar functionality. The plugin is well-written and could work effectively with some adjustments. However, it is outdated and incompatible with the most recent Kedro releases. Moreover, there are compatibility issues with specific datasets, such as [tracking.JSONDataset](https://docs.kedro.org/en/0.18.14/kedro_datasets.tracking.JSONDataset.html) and [tracking.MetricsDataset](https://docs.kedro.org/en/0.18.14/kedro_datasets.tracking.MetricsDataset.html), which are write-only and [cannot be loaded](https://github.com/AnH0ang/kedro-cache/blob/master/src/kedro_cache/framework/hooks/cache_hook.py#L129).

I believe that integrating node caching directly into Kedro's core design would help mitigate such compatibility issues and provide a more robust solution for users.

**Comment by astrojuanlu** [comment] 2024-11-28 13:02
Thanks for opening this issue @froxec ! This is a duplicate of #221, https://github.com/kedro-org/kedro/discussions/837, #2307. Copying this context in the latter.

**Closed by astrojuanlu** 2024-11-28 13:02 UTC
Labels: Issue: Feature Request, Community
