### ISSUE TITLE
Revisit: Make KedroContext a dataclass and add `config_loader` as a property

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1459] opened 2022-04-20 18:58 UTC
# Description
As `KedroSession` now control the lifecycle of Kedro's run, `KedroContext` act like a container and it stores important attributes. Since we now dropped Python 3.6 support, we can make use of Python's `dataclass` to further tidy up `KedroContext`'s constructor code.

todo:
- [x] Make `KedroContext` a dataclass(https://github.com/kedro-org/kedro/pull/1465)
- [x] Add `config_loader` as @property instead of relying the private `context._get_config_loader()` https://github.com/kedro-org/kedro/pull/1505
- [x] Update corresponding document in Starter/Kedro

**Comment by noklam** [comment] 2023-07-30 21:09
This was merged already, but as we approaching 0.19, I want to revise if it's a good idea to freeze `KedroContext`. 
Related Issues

We should also consider how easy for plugin developer to use `KedroContext`. In the past we were more negative about storing context and states in Hooks for following hooks. However in #2690, we may want to document this. If this is not a bad idea, do we need to re-visit the decision we made?

**Comment by noklam** [comment] 2023-08-01 16:54
https://github.com/python/cpython/issues/93133#issuecomment-1660480431

Potentially helpful with the issues that using mock with dataclass or attr.

**Comment by Galileo-Galilei** [comment] 2023-10-28 20:49
I cross-reference #3214 here which is likely a duplicate of this, sorry!

**Comment by noklam** [comment] 2023-10-28 23:50
Thanks for x-ref the issues. The issue has been 1.5 years old and my thinking has changed a little bit as well. I agree with you mostly because:
1. It has not been causing any issue since the hook is added 1.5 years ago.
2. Stateful hook is more common in Kedro now, so users are likely to bump into this problem often.

Basically, I think we can take a middle-ground which is Mutable class + immutable attributes. The key is to use `attrs.setters.frozen`, I mentioned that in https://github.com/kedro-org/kedro/pull/1465/ but honestly I don't remember why I did not use it but go for a full `frozen` class. Would this be sufficient?

```python
import attr
from attrs.setters import frozen

@attr.s
class Foo:
  # A partial frozen class
  bar: int = attr.field(default=0, on_setattr=frozen)

f = Foo()
f.abc = 3 # It's ok to mutate the class
f.bar = 3 # It's not ok to mutate existing attribtue
```

**Comment by astrojuanlu** [comment] 2023-10-29 06:54
Is this possible with plain dataclass? (To avoid the extra dependency if possible)

**Comment by Galileo-Galilei** [comment] 2023-10-29 14:51
## Choosing between ``attrs`` and ``dataclasses``

In the original issue https://github.com/kedro-org/kedro/pull/1465, there are detailed analysis of the pros and cons and justifications to choose over ``attrs``. The conclusion **seems to be that it is much easier to make the class "partially" frozen** (e.g. some attributes are frozen and other are not,namely the one prefixed with an underscore  like ``_hook_manager``) with ``attrs`` rather than with ``dataclasses`` (even if it was possible too with a lot of boilerplate code).  

Since we finally ended up making the entire class frozen, I am not sure why this was relevant in the end, but I may miss someething. This **needs to be reassesed once we figure out if we really want to make the class or some of its attributes frozen**. 

## Should we make some fields frozen? 

If I understand correctly, this was the original motivation of the PR, but I think the following arguments still stands: 

> It has not been causing any issue since the hook is added 1.5 years ago.

So I would be in favor of not freezing anything and use a pure dataclass. This would also helps to get rid of ``attrs`` (the motivation for thsi package was to make only some attributes frozen)  and one less dependency, many less future maintenance problems :)

## Workaround to add fields on a frozen dataclass

I've played a bit around this, and here are some food for thoughts. In a nutshell: 

|Package     |Override existing attribute| Add extra attribute|
|-------------|-----------------------------|---------------------|
|``dataclass``|:white_check_mark:            | :white_check_mark:|
|``attrs``       |:white_check_mark:             | :x:|

This implies that **if we switch to ``dataclass`` instead of attrs, we can keep the exact current behaviour**, but the price is to have a boilerplate code as described in the first paragraph.

#### frozen ``dataclass`` can be overriden and added

```python
from dataclasses import dataclass

@dataclass(frozen=True)
class PointDataClass:
    x: int
    y: int

point_data_class = PointDataClass(x=1, y=1)
point_data_class.z = 2 # # FrozenInstanceError: cannot assign to field 'z'
object.__setattr__(point_data_class, "y", 4)  # works: you can override an existing field
print(point_data_class.y)
point_data_class.__setattr__("z", 2)  # self.__setattr__ does not work: FrozenInstanceError: cannot assign to field 'z'
object.__setattr__(point_data_class, "z", 2)  # object.__setattr__ works! You can add an attribute
print(point_data_class.z) # 2
```

#### frozen ``attrs`` attributes can be overriden and but not added

```python
from attrs import frozen

@frozen
class PointAttrs:
    x: int
    y: int

point_attrs = PointAttrs(x=1, y=1)
point_attrs.z = 2
point_attrs.__setattr__("z", 2)  # self.__setattr__ does not work: FrozenInstanceError
object.__setattr__(point_attrs, "y", 4)  # object.__setattr__ works : you can override an existing field
print(point_attrs.y) # 4
object.__setattr__(point_attrs, "z", 2)  #  # object.__setattr__ does NOT work! You CANNOT add an attribute: AttributeError: 'PointAttrs' object has no attribute 'z'
```

**Comment by merelcht** [comment] 2023-11-21 17:17
Completed in https://github.com/kedro-org/kedro/pull/3300

**Closed by merelcht** 2023-11-21 17:17 UTC
