### ISSUE TITLE
Complete migration off Circle CI

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3415] opened 2023-12-12 15:18 UTC
The release job still lives in Circle CI, as well as the "merge main and develop" and others:

https://github.com/kedro-org/kedro/blob/604f7b2/.circleci/config.yml

https://github.com/kedro-org/kedro/blob/604f7b2/.circleci/continue_config.yml

The day of the major release we were caught by surprise by the fact that the release job was using an old Python version #3414  By having everything under the same system we can avoid this attention split and minimize this risk.

**Comment by merelcht** [comment] 2023-12-13 17:30
This is a duplicate of the tickets in the Github Actions milestone: https://github.com/kedro-org/kedro/milestone/52

**Closed by merelcht** 2023-12-13 17:30 UTC
Labels: Component: DevOps
