### ISSUE TITLE
Reading csv file needs updating v.19.8

### ISSUE THREAD

**Issue by TanjaWinkler** [kedro-org/kedro#4133] opened 2024-08-30 12:58 UTC
## Description
The load_args argument now needs a dictionary as input. In the example the load arguments are just listed without dict brackets, but that does not work anymore.
![Picture 1](https://github.com/user-attachments/assets/d6728473-22d0-4226-a9f6-9c23762c96c2)

The current version would have to be:

load_args: { 
          "sep"; ","
           }

### Documentation page (if applicable)
https://docs.kedro.org/en/0.18.14/kedro_datasets.pandas.CSVDataset.html

**Comment by ElenaKhaustova** [comment] 2024-08-30 15:30
Hello @TanjaWinkler, thank you for opening an issue.

We didn't change the syntax for setting the parameters, and since it's a `.yml` file, it assumes `load_args` is a dictionary without brackets.

Could you please share some context and the actual error you're facing?

**Comment by TanjaWinkler** [comment] 2024-08-30 17:59
Hi there,

If I don't use the brackets, I can't load the CSV - I get an error message about not being able to read the load arguments. When I looked at the documentation within the kedro project to debug I did find example that had the brackets. I added those and it was all working.

All the best,
Tanja

________________________________

**Comment by ElenaKhaustova** [comment] 2024-08-30 18:03
> Hi there, If I don't use the brackets, I can't load the CSV - I get an error message about not being able to read the load arguments. When I looked at the documentation within the kedro project to debug I did find example that had the brackets. I added those and it was all working. All the best, Tanja

Can you please share your configuration file and the error traceback?

**Comment by TanjaWinkler** [comment] 2024-08-30 18:05
I will do it on Monday. I've logged off for the weekend. :)

Have a good weekend yourself.

All the best,
Tanja

________________________________

**Comment by TanjaWinkler** [comment] 2024-09-02 07:44
Hi there,

I somehow can't reproduce the error, but the dictionary still works too - see the following documentation on https://raw.githubusercontent.com/kedro-org/kedro/develop/static/jsonschema/kedro-catalog-0.19.json:

<https://1drv.ms/i/c/d45b4135c0d56cc2/EeRMrNxZKeNLq0WaXwVLe-gBMSXVrO5mvyC5s37mNwPTAg>
[https://uksouth1-mediap.svc.ms/transform/thumbnail?provider=spo&farmid=189968&inputFormat=png&cs=MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDQ3N2U5fFNQTw&docid=https%3A%2F%2Fmy.microsoftpersonalcontent.com%2F_api%2Fv2.0%2Fdrives%2Fb!pVeN1b_UfkiVuyBLs6qIA2Y0t49sogNFt9IIs7ldI7whWyPo70fnQI_wY1n23GK3%2Fitems%2F01WJ2FDWXEJSWNYWJJ4NF2WRM2L4CUW67I%3Ftempauth%3Dv1e.eyJzaXRlaWQiOiJkNThkNTdhNS1kNGJmLTQ4N2UtOTViYi0yMDRiYjNhYTg4MDMiLCJhcHBpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDA0NzdlOSIsImF1ZCI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC9teS5taWNyb3NvZnRwZXJzb25hbGNvbnRlbnQuY29tQDkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImV4cCI6IjE3MjUyNzg0MDAifQ.tRuxaHeHvzVEuoEaloBg35E5YCsskIWEuI03zzim5ZhMJ3gpWRHXHTRbxMroUs6qpogkYBhhK4jUFYqnMOupO9GwCPa4fctsyEE1AjKkpMIRjd0qYu7U4HWS4twspICVJSM303H8v4DoZZWpX-bfucsYKxfUfWUf7w39FuQ4c2JjuJIhb-HCFihFZpfu_kSiEucchKX1qv8k4x40ydnq_dzhjORHywQkwOSSlcB3Fs2zsGmC-lm6WP-hfECr4GrPXoUtv2spLgVJkS56VQbiVzI1gTA0jhawgl1JZvlUeiYLMnWPkDYHAlJ8Bx0dgpaMm2kmL8E2FRqZpDK3m2CCHeMGkAUGsrOxp4iE0NfGhI82aujxYmqPP7jwfTnlKW7JnJ7e79n772RQQltrJyMQQhC7wPqC-457tGK1n516Gh0.vqc0dJEQ8CAK-g4-zEH-jvrENp_rziHfl8IYEokYzCI%26version%3DPublished&width=176&height=176&cb=63860859825]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]Screenshot 2024-09-02 at 08.40.04.png

All the best,
Tanja
________________________________
Von: Tanja Winkler ***@***.***>
Gesendet: Freitag, 30. August 2024 18:05
An: kedro-org/kedro ***@***.***>; kedro-org/kedro ***@***.***>
Cc: Mention ***@***.***>
Betreff: Re: [kedro-org/kedro] Reading csv file needs updating v.19.8 (Issue #4133)

I will do it on Monday. I've logged off for the weekend. :)

Have a good weekend yourself.

All the best,
Tanja

________________________________

**Comment by ElenaKhaustova** [comment] 2024-09-02 08:42
Closing issue as user was not able to reproduce it

**Closed by ElenaKhaustova** 2024-09-02 08:42 UTC
