### ISSUE TITLE
difficulty to read logs with Jupyter (VSCode Dark theme) and new logging

### ISSUE THREAD

**Issue by Debbby57** [kedro-org/kedro#1733] opened 2022-07-28 09:55 UTC
## Description
I'm working on VSCode, and I custom my vscode with the Dark+ color theme. When I use interactive python to work it's really diffcult to read logs because of colors. I need to select them to be able to read them correctly. I notice that the colors are slightly different in interactive python and in terminal.

## Steps to Reproduce
1. use Vscode and  Dark+ color theme 
2. install kedro 0.18.2
3. some code like : 
 ``` python
from pathlib import Path
from kedro.framework.session import KedroSession
from kedro.framework.startup import bootstrap_project
my_path = Path(__file__).resolve().parent.parent 
metadata = bootstrap_project(my_path)
session = KedroSession.create(metadata.package_name, project_path=my_path)
local_context = session.load_context()
my_data= local_context.catalog.load("my_partitioned_data")
 ``` 
you will have : 
![image](https://user-images.githubusercontent.com/57007314/181473668-8ae45549-1b83-4190-8d77-112fe3006aec.png)

4.  
``` python
my_data.items()
```
you will have :
![image](https://user-images.githubusercontent.com/57007314/181473989-a8248b41-e505-47a9-a253-bd9289a83bc0.png)

## Expected Result
I would like to have readable logs.

## Actual Result
logs are difficulty to read.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.2
* Python version used (`python -V`): 3.9.13
* Operating system and version: linux and VSCode with  Dark+ theme

thank you for your help :)

**Comment by datajoely** [comment] 2022-07-28 10:15
Can you run the following command `python -m rich.logging` on your terminal?

![image](https://user-images.githubusercontent.com/35801847/181481724-dccf9447-5132-42a0-b502-65fbd6be680d.png)

I'm using the Dark+ them with Zsh on my end and the logs look like they do above?

**Comment by Debbby57** [comment] 2022-07-28 12:03
thank you for your reply.
I have no problem with my logs in terminal. When I run your command on terminal I have the same logs as you. I only have those color problems when I use the interactive python window (Jupyter) of VSCode. Sorry if my issue wasn't explicit :/

**Comment by datajoely** [comment] 2022-07-28 13:40
@noklam maybe let's group this under the similar databricks issue?

**Comment by noklam** [comment] 2022-07-28 14:23
@datajoely Do you think this is a `rich` problem?

![image](https://user-images.githubusercontent.com/18221871/181542928-668a525c-cffd-4cd5-b738-f0fe737b632e.png)

**Comment by datajoely** [comment] 2022-07-28 14:29
Can we get anywhere with this `color_system` piece?
https://rich.readthedocs.io/en/stable/console.html#color-systems

**Comment by noklam** [comment] 2022-07-28 14:53
@datajoely Doesn't seem to have any effect. I think it's likely some hook buried in `rich.pretty.install()`

**Comment by datajoely** [comment] 2022-07-28 14:56
Maybe we should provide a readymade console to the `install` method?

https://github.com/Textualize/rich/blob/2ee992b17ef5ff3c34f89545b0d57ad4690a64fc/rich/pretty.py#L198

**Comment by datajoely** [comment] 2022-07-28 15:06
I guess we need to set this global beforehand? https://github.com/Textualize/rich/blob/2ee992b17ef5ff3c34f89545b0d57ad4690a64fc/rich/__init__.py#L30

**Comment by AntonyMilneQB** [comment] 2022-07-29 10:35
I can confirm this is a problem with Jupyter specifically (not IPython) and not limited to VSCode. It boils down to how rich handles the colour scheme.

Here's what I get with `kedro ipython` and `session.run()`:
![image](https://user-images.githubusercontent.com/49395058/181740230-9e287814-2d21-4faf-9961-662f68f8ecfb.png)

Here's what I get with `kedro jupyter lab` and `session.run()`:
![image](https://user-images.githubusercontent.com/49395058/181740278-0cc38725-0581-41f2-a4c4-af25365d5add.png)

The colour schemes used here are clearly a bit different. The one I see in Jupyter is the same as the one that you see in VSCode also.

Ultimately this is due the fact that rich seems to render logging using a slightly different colour scheme in Jupyter compared to on the console. e.g. using [this example from the docs](https://rich.readthedocs.io/en/stable/logging.html) in a plain (non-Kedro) Jupyter notebook:
![image](https://user-images.githubusercontent.com/49395058/181740772-ea7195b9-a78d-4f14-99cc-181fd3ef4d53.png)
Note that `rich.pretty.install` is not what gives this colour scheme this since the above notebook did not have that run.

So I think what we're seeing here is nothing in particular to do with the Kedro setup but the fact that rich uses a different colour scheme for logging in Jupyter vs. on the console. I don't know if that's deliberate or not - we should ask there.

**Comment by noklam** [comment] 2022-07-29 11:23
@AntonyMilneQB I agree this is more a `rich` issue and we should ask there.

But I think `rich.pretty.install` did play some roles here. It could be both the `RichHandler` and the `__repr__`  

This example should be enough to prove this.
![image](https://user-images.githubusercontent.com/18221871/181748011-9a86e4e4-f168-49ec-bfcc-acc3de5538c4.png)

**Comment by AntonyMilneQB** [comment] 2022-07-29 14:06
Ah yes, what I meant to say was that the `rich.pretty.install` shouldn't affect the colour of the log messages. As you show, it affects the appearance of the REPL, which is less important but still doesn't seem to be handled nicely by rich in Jupyter when there's not a light background.

Again, this works fine on IPython and is just a problem on Jupyter:
![image](https://user-images.githubusercontent.com/49395058/181776258-46468dfe-b296-4ad4-9941-107df21a7d7f.png)

**Comment by noklam** [comment] 2022-08-16 08:37
I'll add my own experience, I just install `jupyterthemes` for Jupyter Notebook and it doesn't work well with the dark theme. Ideally `rich` is smart enough to handle most of the situations, but it's also inevitable it will crash with plugins. I can imagine it will interfere with dark-themes browser plugin as well. In that case, we should have an easy way to disable the `rich` REPL .

![image](https://user-images.githubusercontent.com/18221871/184835297-9bb95f42-9d7b-4716-85ed-9b70eb9f4705.png)

**Comment by astrojuanlu** [comment] 2023-12-18 14:44
Essentially https://github.com/Textualize/rich/issues/505, https://github.com/Textualize/rich/issues/2484

**Comment by astrojuanlu** [comment] 2024-07-21 22:06
Rich is not doing anything about this issue, and in theory there are themes one can customise but it's not clear to me how to apply them.

Closing this as won't fix. Stay tuned to the linked issues for upcoming changes in how we manage logging and our rich integration.

**Closed by astrojuanlu** 2024-07-21 22:06 UTC
