### ISSUE TITLE
[DOCS] Pyspark integration docs are outdated and don't work

### ISSUE THREAD

**Issue by MigQ2** [kedro-org/kedro#4166] opened 2024-09-15 21:19 UTC
## Description
I believe [Pyspark integration docs](https://docs.kedro.org/en/0.19.8/integrations/pyspark_integration.html) are outdated and don't work well with the new `OmegaConfigLoader` 

It recommends to put spark config in `conf/base/spark.yml` and then using `parameters = context.config_loader.get("spark*", "spark*/**")` to load it. 

However, when I do it that way,  `context.config_loader.get("spark*", "spark*/**")` returns the string `'spark*/**'` 

The way I solved it was:

1. Create the yml file in `conf/base/parameters/spark.yml` with the following structure:

```yaml
spark_config:
    spark.driver.maxResultSize: 3g
    spark.scheduler.mode: FAIR
```

2. Load the spark config using `spark_config = self.config_loader.get("parameters")["spark_config"]` instead of `parameters = context.config_loader.get("spark*", "spark*/**")` (I renamed `parameters` to `spark_config` to make it more clear that it's different from the root of params)

If there's another best practice or another recommended/opinionated way of managing this please let me know. 

### Documentation page (if applicable)
[Pyspark integration docs](https://docs.kedro.org/en/0.19.8/integrations/pyspark_integration.html)

**Comment by merelcht** [comment] 2024-09-16 11:02
Thanks for reporting @MigQ2 , this looks like a duplicate of https://github.com/kedro-org/kedro/issues/4118. I'll close this issue and prioritise the other one.

**Closed by merelcht** 2024-09-16 11:02 UTC
