### ISSUE TITLE
Gitignore should be excluding the local configuration

### ISSUE THREAD

**Issue by corymckinsey** [kedro-org/kedro#2613] opened 2023-05-29 17:52 UTC
## Description

The .gitignore contains:
```
# ignore all local configuration
conf/local/.gitkeep
!conf/local/.gitkeep
```
But, should contain:
```
# ignore all local configuration
conf/local/
!conf/local/.gitkeep
```

## Context
My local configuration was being committed to GitHub and DBX was syncing my local configuration as well.

## Steps to Reproduce
1. Create file in local directory
2. Run git status

## Expected Result
The file shouldn't appear in the result

## Actual Result
The file can be added + committed

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version: 0.18.8
* Python version: 3.10.11
* Operating system and version: Mac

**Comment by astrojuanlu** [comment] 2023-05-29 17:55
Hi @corymckinsey, thanks for opening this issue. Would you please indicate how did you create your project, if you know it?

This is the contents of `.gitignore` for the default project:

https://github.com/kedro-org/kedro/blob/2f248a4fc650f44d40323466b18d436024d83c75/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.gitignore#L4-L6

So, in principle `kedro new` should not be affected.

**Comment by noklam** [comment] 2023-05-29 17:55
Which starter are you using?

**Comment by noklam** [comment] 2023-05-29 17:55
Which starter are you using?

**Comment by corymckinsey** [comment] 2023-05-29 17:58
Odd. I created the project using `kedro new`. Again the version I used was 0.18.8.

**Comment by astrojuanlu** [comment] 2023-05-29 18:32
I even did [a search with Sourcegraph](https://sourcegraph.com/search?q=context:global+%22conf/local/.gitkeep%22&patternType=standard&sm=1&groupBy=repo) and cannot locate the origin of that config.

I don't have an explanation of why that happened, and sorry you had a bumpy experience. But it looks like there's nothing we have to change on our side.

I'm closing but if you can reproduce this error or encounter it again, feel free to drop a comment and we will reopen.

**Closed by astrojuanlu** 2023-05-29 18:32 UTC
