### ISSUE TITLE
INFO level logging is missing on Databricks

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3639] opened 2024-02-21 15:19 UTC
## Description

On Databricks:
<img width="1100" alt="image" src="https://github.com/kedro-org/kedro/assets/18221871/c1b94ad2-5cfb-4616-b68f-634f41fdcaa7">

On IPython:
<img width="730" alt="image" src="https://github.com/kedro-org/kedro/assets/18221871/a1260a51-0534-4685-ba27-ef0e4e4b232a">

## Context

I assume all `INFO` level logging are not visible, I had issues with Databricks so I cannot run the pipeline.

## Steps to Reproduce
1. Load up the `%load_ext kedro.ipython` 

## Expected Result

The `info` logging should be shown on Databricks.

## Actual Result

The `INFO` loggging is missing

**Comment by DimedS** [comment] 2024-04-23 14:48
Hi @noklam , looks like it works well on my side. Could you please share your setup? Mine is Azure Databricks on Platform McK.
With %load_ext:
<img width="1484" alt="Screenshot 2024-04-23 at 15 36 16" src="https://github.com/kedro-org/kedro/assets/40151847/ede1f81f-9c85-4589-8835-7b8441695d39">

and when running a pipeline:
<img width="953" alt="Screenshot 2024-04-23 at 15 36 56" src="https://github.com/kedro-org/kedro/assets/40151847/575f2cb7-0032-4840-a030-688933ee61e6">

**Comment by noklam** [comment] 2024-04-23 15:06
git@github.com:noklam/databricks-iris-19.git

I have the old repostory here, I don't think I have much time to look at it this week. I tried the platform mck but I struggled with setting up a databricks instance. We can either connect next week or if you could quickly clone the repo and see if it works.

**Comment by DimedS** [comment] 2024-04-24 13:59
> [git@github.com](mailto:git@github.com):noklam/databricks-iris-19.git
> 
> I have the old repostory here, I don't think I have much time to look at it this week. I tried the platform mck but I struggled with setting up a databricks instance. We can either connect next week or if you could quickly clone the repo and see if it works.

I tried your project and it works well. I can see the INFO logs. Let's discuss it further next week.

**Comment by noklam** [comment] 2024-05-02 14:29
I couldn't reproduce the issue. Tried with 0.19.2 (the version that I reported this) and the latest 0.19.5, we can close this if there is nothing more to do.

**Comment by DimedS** [comment] 2024-05-03 08:59
We have confirmed that INFO logging messages are visible and functioning properly on Databricks. The issue is no longer relevant, so we are closing the ticket.

**Closed by DimedS** 2024-05-03 08:59 UTC
Labels: Bug Bash :bug:
