### ISSUE TITLE
Add ability to Specify a "root" for `DataCatalog.from_config`

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2965] opened 2023-08-23 16:55 UTC
## Description

Related https://github.com/kedro-org/kedro/issues/2924#issuecomment-1690280993

## Context

```
conf_catalog = config_loader["catalog"] # config
conf_catalog = _convert_paths_to_absolute_posix(Path("../../").resolve(), conf_catalog) # config/catalog
catalog = DataCatalog.from_config(conf_catalog) # catalog
catalog.load("example_data")
```
Currently using `context.catalog` (framework) wlil do some magic path conversion. When user use `DataCatalog` alone they don't have the ability to define where is the "root" directory.

It contradicts with `kedro` suggesting `notebooks/` and `data`. Because if notebook is inside `notebooks`, you would need to use `../` inside the `catalog.yml`. This is bad because it prevent the `catalog.yml` to be reused and assume that all the notebook will has to be in the same folder (preventing multi-users sharing 1 catalog)

## Requirements
This should be:
- backward compatible - no impact on existing framework user
- notebook/library user should be able to configure the "root" of the data source

Consider:
> To note, even if using a root, the converted keys are still hardcoded, so probably we should do something about it too (say that some user wants to call it file_path) https://github.com/kedro-org/kedro/issues/2965#issuecomment-1690319815

## Possible Implementation

See detail discussion
```python
DataCatalog.from_config(root="../data") 

```
the new_argument could be name `data_source`, `root` etc (undecided, this should be taken into consideration when implemented)
https://github.com/kedro-org/kedro/issues/2924#issuecomment-1690280993

**Comment by astrojuanlu** [comment] 2023-08-23 17:01
To note, even if using a `root`, the converted keys are still hardcoded, so probably we should do something about it too (say that some user wants to call it `file_path`)

**Comment by astrojuanlu** [comment] 2023-08-26 14:46
xref https://github.com/kedro-org/kedro/issues/1934

**Comment by noklam** [comment] 2023-08-30 15:15
cross reference an user [question](https://kedro-org.slack.com/archives/C03RKP2LW64/p1693408000223539) - pinging the magic bot to convert this into linen link...

**Comment by astrojuanlu** [comment] 2023-10-02 08:41
In our internal discussions it was noted by @yetudada that, regardless of what name we give to this parameter, we would still be making `DataCatalog.from_config` perform 2 different operations:

1. Turn the JSON config into the appropriate initialization parameters (current behavior) and
2. Convert the local filepaths to absolute (new, proposed behavior)

@yetudada pointed out that Intake has a `{{ CATALOG_DIR }}` template variable they use in front of relative paths https://intake.readthedocs.io/en/latest/catalog.html#yaml-format however, it was already noted in our Tech Design session https://github.com/kedro-org/kedro/issues/2924#issuecomment-1690280993 that this requires a config loader to work, which is something we don't want.

Personally I don't think it would be productive to rehash the discussion we already had, since we explored and evaluated a number of options and no new ideas have been presented. It might be the case that no perfect, clean solution exists.

On the other hand, my initial concern that the list of hardcoded key names in the session is still not transparent https://github.com/kedro-org/kedro/issues/2965#issuecomment-1690319815 hasn't been addressed yet. As a reminder, it is

https://github.com/kedro-org/kedro/blob/bbed0f1690c9da7f6768bad38365ab79120f87f0/kedro/framework/context/context.py#L91-L92

So, to make `DataCatalog.from_config(..., local_root="...")` do the conversion, we'd need to have that list of hardcoded keys as well. Alternatives like `DataCatalog.from_config(..., local_filepath_keys=("filename", "filepath", "path"))` could be considered.

**Comment by astrojuanlu** [comment] 2023-10-03 19:51
Another comment from @yetunde: https://github.com/kedro-org/kedro/issues/2819#issuecomment-1744787202

> - What is the most intuitive way to load relative paths in `catalog.yml`? `source="../data"` is really confusing and I'm not sure intuitive naming will help this. Additionally, we would have to teach this concept to new users of Kedro because we only teach Kedro using local data. And, this concept only appears for local data; our experience is not consistent when compared to how we would use s3 or Azure Blob Storage.
> - How do other libraries handle relative paths in configuration?

**Comment by jasonmhite** [comment] 2023-10-10 13:39
Forgive me for rehashing as I try to wrap my head around this, but if I understand things correctly, it seems like the core of this issue is that the code for loading the data catalog doesn't have access to the project configuration, or at least sometimes it will not? And this is a deliberate design decision because the goal is to decouple the catalog instantiation from the runtime?

It seems this is most often going to be an issue with `kedro ipython` and/or `kedro jupyter` since those are the most likely suspects where the interpreter is going to change from the project root directory (especially Jupyter, since if you click into the notebooks directory it always changes directories). A crude but effective solution could be to simply add to the initialization magic for jupyter/ipython something like `os.chdir(context.project_path)` or likewise.

I can't say I fully understand what's going on under the hood, but generally `project_path` seems special apart from the other project configuration. Having a way to access it anywhere in a kedro invocation (be it in a pipeline, in a dataset implementation, etc) seems like a valid case for special treatment. It seems like accessing the project context used to be possible in older versions but I think this was removed/refactored? I had a bit of a hard time following that part of the code.

**Comment by astrojuanlu** [comment] 2023-10-11 10:52
hi @jasonmhite , thanks for chiming in:

> it seems like the core of this issue is that the code for loading the data catalog doesn't have access to the project configuration, or at least sometimes it will not? And this is a deliberate design decision because the goal is to decouple the catalog instantiation from the runtime?

that's correct.

We're trying to solve for a set of requirements that is very difficult to satisfy, namely:

1. The solution must make using `DataCatalog` easier to use as a standalone component, and enable users to easily share `catalog.yml` files.
   - This means that, for catalog files containing local paths to be easily shareable, they should not use absolute paths (the reproducibility killer). But relative paths depend on the current working directory and where the file is placed. That's the main problem we're solving for.
   - Notice that this does _not_ affect database connections nor remote files. Which, I've been told, is the large majority of cases for professional teams.
2. The solution must not introduce coupling between `DataCatalog` and other objects (like `OmegaConfigLoader`) or Kedro framework assumptions.
   - This rules out solutions that involve having a template variable `{{ project_root }}` because it would make the `DataCatalog` responsible of resolving that variable.
3. The solution should be backwards compatible with existing catalogs. Existing catalogs all use relative paths for local files. This relative path is mangled by Kedro framework, whereas the `DataCatalog` object doesn't do anything about it.
   - This again rules out solutions that involve having a template variable `{{ project_root }}` because no existing Kedro catalogs use it.

**Comment by jasonmhite** [comment] 2023-10-11 13:14
@astrojuanlu Is it possible to push it into the Dataset implementation? You could extend the base class to add a member try to resolve the project root directory if it is available from the context , otherwise resolve to the cwd. Then it becomes the responsibility of the implementation to actually *use* that base directory. It wouldn't fix the issue automatically, but at least it would then be possible to update a dataset implementation to handle things correctly.

**Comment by astrojuanlu** [comment] 2023-10-20 13:42
We discussed this again today with @yetudada, @idanov and @merelcht.

This is how the error manifests:

![image](https://github.com/kedro-org/kedro/assets/316517/3a9b7bd3-caa5-4d6d-b476-70c27462a4de)

@jasonmhite we considered your idea but we thought that it would require too much work on all datasets [TBC]

Historical perspective: the paths are converted to absolute because of https://jira.quantumblack.com/browse/KED-1796 (internal link)

> 1. Kedro expands relative local paths from catalog using `pathlib.Path`, which results in a `WindowsPath` instance on Windows
> 2. This `WindowsPath` is stringified and is then passed to `PickleDataSet`, which in turn converts it to `PurePosixPath` and passes it to `AbstractVersionedDataSet` initialiser 
> 3. `WindowsPath` -> str -> `PurePosixPath` breaks things and should rather be something like `WindowsPath.to_posix()` -> `PurePosixPath`
> 4. Ideally Kedro should not pass (potential) Windows paths around as strings

More relevant issues: https://github.com/kedro-org/kedro/issues/412

We decided to try to improve the error message in this case, and if we do add a parameter then give it a name that relates to the Current Working Directory.

**Comment by astrojuanlu** [comment] 2023-10-30 17:32
Decision turned into #3248, closing this ticket.

**Closed by astrojuanlu** 2023-10-30 17:32 UTC
Labels: Issue: Feature Request
