### ISSUE TITLE
using np. random.seed in one pipeline run is successful but fails to reproduce same dataset when kedro run is executed 

### ISSUE THREAD

**Issue by jazz215** [kedro-org/kedro#4103] opened 2024-08-19 01:58 UTC
## Description
using np. random.seed in one pipeline run is successful to reproduce a dataset but fails to reproduce same dataset when kedro run or full pipeline is executed 
## Context
I am trying to reproduce a dataset where uses noise np. random.uniform. I am using np.random.seed  to generate same noise. I have also tried using deterministic noise, but have the same issue 

## Steps to Reproduce

* Kedro version used (`pip show kedro` or `kedro -V`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by DimedS** [comment] 2024-08-19 19:00
Hi @jazz215, thanks for reporting this! `np.random.seed` should normally ensure reproducibility, even with `kedro run`. If it's not working as expected, it could be due to differences in execution context, parallel processing, or pipeline caching.

Could you share more details, such as how you're setting the seed and any relevant code snippets? This will help us better understand the issue and offer a solution.

**Comment by ElenaKhaustova** [comment] 2024-08-27 11:25
Hi @jazz215, It's a common issue when using a random seed. For example, if you have two nodes doing random sampling, you get a different result if you run one node at a time compared to running both. So, the result when running one pipeline and running multiple pipelines can be different.

**Comment by ElenaKhaustova** [comment] 2024-08-27 11:28
Closing as it's a common issue that doesn't have any straightforward solution

**Closed by ElenaKhaustova** 2024-08-27 11:28 UTC

**Comment by noklam** [comment] 2024-08-27 11:55
To supplement this:
- This is not specific to Kedro, if you try to run a program in a single run, it will be different to when you run it partially.
  - If this guarantee is important, you may need to reset the seed for every single node, though you need to understand what's the consequence.
- If you are using `SequentialRunner`, for the same set of nodes, you should get the same result as the order of execution is deterministic.
  - If you are using `Threadrunner` or `ParallelRunner`, this cannot be guaranteed because this is non-deterministic by nature.
