### ISSUE TITLE
You can't manually enforce the order of local and plugin-based hooks

### ISSUE THREAD

**Issue by foxale** [kedro-org/kedro#1939] opened 2022-10-17 12:02 UTC
## Description & Context
Some hooks come from plugins (like `kedro-mlflow`), whereas some may come from local hooks (like [those](https://kedro.readthedocs.io/en/stable/hooks/examples.html)). Currently, if many plugins and local hooks implement e.g. `after_pipeline_run`, there is no way to manually enforce order in which all those functions will be invoked. 

This causes problems such as [this one](https://github.com/Galileo-Galilei/kedro-mlflow/issues/366).

Also, while writing this post I realized another problem, which is using the name "hook" for both hook functions (e.g. `after_pipeline_run` hook function) and hook classes (e.g. `DataCatalogHook` class)

## Steps to Reproduce
Available in the linked post above.

## Expected Result
I assume we should be able enforce the order of hooks, assign them some priority or rules.

## Your Environment
* kedro 0.18.3
* Python 3.9.14

**Comment by MerelTheisenQB** [comment] 2022-10-17 12:18
Hi @foxale, hooks have been designed to run in the LIFO of registration (see https://kedro.readthedocs.io/en/stable/hooks/introduction.html#registering-your-hook-implementations-with-kedro).

How would you envision being able to assign priory rules? Per Hook class or at the hook function level?

**Comment by foxale** [comment] 2022-10-17 12:29
Yes, I saw that before — but from what I understood and observed, there are separate queues for local hooks vs. plugin-based hooks. You can influence the registration order indirectly and directly with [hook function annotations](https://docs.pytest.org/en/7.1.x/how-to/writing_hook_functions.html#hook-function-ordering-call-example). 

I would want to decide, that `kedro-mlflow`'s hook should be the last hook executed, and second to last my custom `UploadLogsToMLflowHook`. How to do that in a user friendly way, that's a tough question.

**Comment by noklam** [comment] 2022-10-17 12:51
https://github.com/kedro-org/kedro/blob/d019eda0add1ec4efbd652f419d4b20edbab3f25/kedro/framework/session/session.py#L110-L113

I believe this is how Kedro works currently (in-order)
1. Register hooks `settings.py` which run in the LIFO queue (project based)
2. Prepare the `setup.py` `hooks` entrypoints (installed plugins)
3. Exclude any plugin specified in `settings.py` and register the result of 2&3.

I think I had some discussion with @AntonyMilneQB about this before - there wasn't any clear conclusion. How does `pytest` plugins handle this? In general, I don't like the idea that the plugin needs to be aware of the existence of other plugins, this creates implicit dependencies and is hard to debug. However, I understand that `mlflow` (or quite a few experiment tracking tools also operates on some global session) so specifying the order is a reasonable thing to do.

**Comment by foxale** [comment] 2022-10-17 14:25
Thanks for the context @noklam! I checked `pytest` and `pluggy` docs, and from what I see they only offer the default LIFO queue based on hook registration order, and `try_first` / `try_last` methods.

One way would be implement a mechanism to put hooks in order on `kedro` side and then leverage `pytest`'s LIFO order to get reproducible results. Here's one exemplary idea:
- generate and constantly update the default order of project based + plugin based hooks (for each hook), so that the user is aware what exactly is going on with the project and in which order
- allow user to enforce the order of all hooks via project config and automatically validate its correctness

*Side note:* that could actually be used to enrich `kedro-viz` execution graph, or generate a separate "pipeline execution flow" graph

*Side note 2:* that could fix #1935 as well.

**Comment by noklam** [comment] 2022-10-17 15:46
@foxale I think this is supported already, although we don't have docs to spill this out clearly. 


* In general, I think the order should not matter, they should operate independently. Auto-registered hooks shouldn't need to be aware of the existence of other plugins - this would be the common case.
* In special cases you need the fine grain control of order - you can import these hooks into your project directly and disable the automatic one. 

```py
# settings.py
from kedro_mlflow.hooks import MLflowHooks  # I make these import up but you get the point
DISABLE_HOOKS_FOR_PLUGINS = ("kedro-mlflow",)
HOOKS = (MLflowHook(), YourHook(),)  # This is always a LIFO queue - in fact the LIFO order is inherit from `pytest` already

```

One thing we may consider is to do the auto-register hook before the project hooks, but this is up for discussion.

**Comment by foxale** [comment] 2022-10-17 16:22
Awesome. I guess that solves most cases (including mine), with the exception of those that require different orders for different hook functions.

**Comment by merelcht** [comment] 2023-01-03 12:16
Closing this issue as the problem is solved. Feel free to re-open and continue discussing if you encounter further issues with this!

**Closed by merelcht** 2023-01-03 12:16 UTC
