### ISSUE TITLE
Drastically simplify the default project template

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#2149] opened 2022-12-20 16:56 UTC
## Description & Context

Our users have the perception that Kedro is a complicated and needs a lot of boilerplate. This perception is to a large extend fuelled by the overly complete template we generate by default. While having the complete template is still useful to some users, many find it fairly complicated.

We should look into drastically simplifying the current default template and move the current one to the list of officially supported starters under the name of `legacy-default-starter`, `full-template`, `full-kedro-project` or something like that. Having a smaller and simpler initial template will significantly reduce the cognitive overload to new users of Kedro and thus ease the onboarding experience.

## Possible Implementation

Currently our template includes the following folders and files:
 - conf/
 - data/
 - docs/
 - logs/
 - notebooks/
 - src/
 - .gitignore
 - pyproject.toml
 - README.md
 - setup.cfg

Most of those folders are not needed and can be safely removed, namely:
 - all data/ subfolders (and even the data/ folder itself)
 - docs/
 - logs/
 - notebooks/

Moreover, we should move away from using `setup.py` and make all Kedro starters use only `pyproject.toml` and `setup.cfg`, since this is how the Python ecosystem is evolving.

We should also revise the README.md and make sure it has up-to-date quick-start instructions on how to use Kedro and where to write your project code, how to load data and how to deploy it.

## Possible Alternatives

Create a minimal starter and recommend it always in all trainings over the full template.

**Comment by astrojuanlu** [comment] 2023-01-31 16:50
xref #2152

**Comment by merelcht** [comment] 2023-03-01 17:39
We discussed this issue in **technical design** on the 1st of March:

**The action point that came out of the discussion:**

- [ ] Create sub-tasks to discuss/investigate the removal of each folder separately. 


**Longer summary of what was said:**
The proposal to remove all directories was met with various opinions. Some points discussed:

- Can we even remove the `logs/` folder? This was pending user research, but the verdict is it can be removed as confirmed by @AntonyMilneQB  and @amandakys 
- If we remove all these directories, should we then remove them from the starters as well? No, the starters are a good way of showing how you could potentially order your data, notebooks etc. So the staters should stay as they are.
- We could potentially keep the `data/` folder, but just remove the sub-directories. Or even for all directories we could add a `README.md` which explains the directory can be removed or how else it could be used.
- Would removing these directories actually make future steps e.g. packaging a project harder, because users might then have added files in wrong places e.g. notebooks in `src/` because there wasn't any other obvious place

A large part of the discussion also revolved around the Kedro value proposition: 
- Kedro being opinionated is an important part of the value proposition, and some people have voiced confusion when some of the commands we deprecated using a data driven approach actually went away
- Removing parts of the template made several people wonder if that also reduces the value of Kedro as a opinionated framework that uses SWE best practices and guides users in doing the same
- If we do reduce the template we need to update our recommendation and messaging so it's consistent with this slimmed down version of Kedro.
- @amandakys rightfully said that this topic of opt-in vs opt-out comes up in different forms and shapes from time to time and that we should take a step back and try to have a more coherent vision to avoid having such discussions

**Comment by yetudada** [comment] 2023-09-04 09:56
I'm going to close this issue because it's been replaced with tickets that we're working on 🎉

**Closed by yetudada** 2023-09-04 09:56 UTC
Labels: Issue: Feature Request, Stage: Technical Design 🎨, Type: Parent Issue
