### ISSUE TITLE
Running distributed training on PyTorch Lightning runs the same node multiple times

### ISSUE THREAD

**Issue by ytan101** [kedro-org/kedro#2049] opened 2022-11-23 07:59 UTC
## Description
I have 2 nodes in my pipeline (train + evaluate) that I have added to my pipeline registry. When I call trainer.fit(), the entire training node is ran twice. Is this the expected behaviour?

## Context
I wish to pass a single output to be logged into the DataCatalog, but now I am getting an error when logging the outputs as the train node is ran twice. This also causes the evaluate node to be called twice as well. However, I only expect the train node to be called once.

## Steps to Reproduce
My current code for the training node is as follows

```
from pathlib import Path

import pytorch_lightning as pl

# import os
# import glob

from pytorch_lightning.callbacks import ModelCheckpoint, LearningRateMonitor
from pytorch_lightning.loggers import MLFlowLogger
from rich import print
from typing import Dict
from easydict import EasyDict as edict


def train(args: Dict) -> str:
    mlf_logger = MLFlowLogger(
        experiment_name="pl-train"
    )

    args = edict(args)
    cfg_from_yaml_file(args.cfg_file, cfg)

    cfg.DATASET_NAME = "/".join(args.cfg_file.split("/")[4:-1])
    cfg.MODEL_NAME = Path(args.cfg_file).stem
    cfg.OPTIMIZATION.NUM_EPOCHS = args.epochs
    cfg.WORKERS = args.workers
    cfg.SYNC_BN = args.sync_bn

    output_dir = (
        cfg.ROOT_DIR
        / "output"
        / "train"
        / cfg.DATASET_NAME
        / cfg.MODEL_NAME
        / args.extra_tag
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    cfg.OUTPUT_DIR = output_dir

    checkpoint_callback = ModelCheckpoint(save_top_k=-1, save_on_train_epoch_end=True)
    lr_monitor = LearningRateMonitor(logging_interval="step")

    detector = LightningDetector(cfg)

    trainer = pl.Trainer(
        logger=mlf_logger,
        accelerator="gpu",
        devices=2,
        strategy=ddp_find_unused_parameters_false,
        default_root_dir=output_dir,
        max_epochs=1,
        num_sanity_val_steps=0, 
        check_val_every_n_epoch=0,
        gradient_clip_val=cfg.OPTIMIZATION.GRAD_NORM_CLIP,
        callbacks=[checkpoint_callback, lr_monitor],
        log_every_n_steps=50
    )

    print("\n\nStarting the training")
    trainer.fit(detector)

    # latest_checkpoint = get_latest_checkpoint_path(
    #     str(output_dir), str(mlf_logger.run_id)
    # )

    # cfg.CHECKPOINT_PATH = latest_checkpoint

    mlf_logger.log_hyperparams(cfg)

    print("hello")
    print("*******************************")

    return {
        "train_checkpoint_folder": str(output_dir),
    }
```

## Expected Result
I expect my train node to be ran once and then call the eval node once

## Actual Result
Train node is being ran twice, and each train node calls an eval node after

When evaluate is called after train (`kedro run`), I get an error about the local_rank being out of range

![image](https://user-images.githubusercontent.com/46697944/203481625-5538ab79-e302-4a25-967e-667c770a948d.png)

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.2
* Python version used (`python -V`): 3.10.6
* Operating system and version: Ubuntu 20.04

**Comment by jmholzer** [comment] 2022-12-02 11:49
Hi @ytan101, could you share the code for the pipeline being run? Thanks.

**Comment by merelcht** [comment] 2023-01-18 14:56
Hi @ytan101, do you still need help with this issue?

**Comment by merelcht** [comment] 2023-02-06 10:39
I'm closing this issue for now. Feel free to re-open this issue again if you're still having problems with it in the future.

**Closed by merelcht** 2023-02-06 10:39 UTC
Labels: Community, Tech support

**Comment by jasonmhite** [comment] 2023-08-18 15:27
I'm actually encountering this issue, or something related to it.

Specifically when using Pytorch/Lightning's distributed data parallel strategy to run multi-GPU training. The way DDP works is that when you start up training it basically re-imports your code in parallel on each worker process simultaneously. I thought I could work around this by running all my nodes right up to the point that the training in serial, save the trainer object, then just do `kedro run --nodes=train_model` so that the re-import would just run load up the trainer object and go instead of re-running the whole script. This almost works, errors out at the end with
![image](https://github.com/kedro-org/kedro/assets/868722/70bc5e7c-99a2-40f2-8372-8be1f4c79c37)

It seems what is going on is that DDP is re-running several Kedro sessions simultaneously. They are able to see each other and proceed with the training, but when the training ends and I go to serialize the model as the output each separate session is stepping on each other with the experiment tracking session store. Am I just doing it wrong?

**Comment by astrojuanlu** [comment] 2023-08-18 15:33
Hi @jasonmhite, the issue was closed because we didn't have enough details, so a MWE would help us a lot. Happy to reopen when we can reproduce it.

**Comment by jasonmhite** [comment] 2023-08-22 18:38
@astrojuanlu Well ok I thought I understood this issue, but when I tried to replicate in a MWE things work perfectly. The problem may be an issue related to how GluonTS (time series library that is built on top of pytorch/lightning for model training) handles training and not Kedro. 

I thought running this project https://github.com/jasonmhite/kedro-multigpu-debug-example with `kedro run --params="devices=2"` would trigger it but it seems not. If I can isolate the issue better I will come back but I guess for now you can disregard.
