### ISSUE TITLE
What are the user needs for the catalog API?

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1978] opened 2022-10-26 13:24 UTC
## Description
The catalog API is an old component of Kedro. It can do with refactoring. In order to re-design the API we need to find out what are user needs are for it. 

Some of the questions that need to be answered:
- Why do users need to access datasets from the catalog directly? 
- Why do users need to get the dataset filepath?

## Context
https://github.com/kedro-org/kedro/issues/1778

## Target users
- Advanced users: those who interact with the API directly
- Plugin developers + `kedro-viz` team

**Comment by astrojuanlu** [comment] 2024-02-21 14:43
To be expanded: https://github.com/kedro-org/kedro-plugins/pull/557#discussion_r1495947847

**Comment by astrojuanlu** [comment] 2024-02-22 10:57
## Introduction

The `DataCatalog` Python class centralises access to data in Kedro projects. Its use is invisible for regular users (that mostly interact with the YAML API by defining a `catalog.yml` file) but it is extensively accessed by plugins. Instances `DataCatalog` are passed to several hooks, including `after_catalog_created`, the Node hooks, and the Pipeline hooks. `DataCatalog` has existed in its current form since basically [_forever_](https://github.com/McK-Private/private-kedro/blob/0.14.0/kedro/io/data_catalog.py) (private link).

> [!NOTE]
> From now on, _users_ refers to users of the `DataCatalog` Python class, which we could consider "advanced users".

Internally, a `DataCatalog` instance is essentially a dictionary that maps dataset names to dataset objects:

https://github.com/kedro-org/kedro/blob/436d17e133aa5aefa7bc07f8154f59a63164294d/kedro/io/data_catalog.py#L142

Said dataset objects, at present subclasses of `AbstractDataset` (unimportant implementation detail), contain the _load_ and _save_ logic for specific data formats and Python libraries. For example, `pandas.CSVDataset` knows how to load and save CSV files using the pandas library.

## Problem

The `DataCatalog` has a number of [public methods and properties](https://docs.kedro.org/en/latest/api/kedro.io.DataCatalog.html). Notably, `DataCatalog.load` and `DataCatalog.save` allow users to load and save data. The way this works is by delegating the actual load and save operations to the underlying dataset:

https://github.com/kedro-org/kedro/blob/436d17e133aa5aefa7bc07f8154f59a63164294d/kedro/io/data_catalog.py#L490

To access the underlying dataset objects, on the other hand, `DataCatalog` offers only one undocumented public property, aptly named `.datasets`, that retrieves a _frozen_ version of the loaded datasets:

https://github.com/kedro-org/kedro/blob/436d17e133aa5aefa7bc07f8154f59a63164294d/kedro/io/data_catalog.py#L187

This was introduced in https://github.com/McK-Private/private-kedro/pull/84 (private link) to "Addresses issue raised / feature requested regarding the ability to view which datasets are available in the data catalog via tab completion in an ipython or jupyter session."

The full rationale behind having this _frozen_ got lost ~~like tears in rain~~ in a Jira ticket that's no longer accessible. However, allowing the users to _inject_ datasets during the session would probably be a recipe for trouble, and hence this was deliberately disabled:

https://github.com/kedro-org/kedro/blob/436d17e133aa5aefa7bc07f8154f59a63164294d/kedro/io/data_catalog.py#L121-L128

The problem is that, _for some reason_, Kedro plugins tend to use the private APIs instead of the public frozen list of datasets. For example:

- Kedro-Viz uses `DataCatalog._get_dataset` (originally introduced in https://github.com/McK-Private/private-kedro/pull/404/ (private link) to serve our versioning) https://github.com/kedro-org/kedro-viz/blob/fdcda72f13e406ed7a2cbac5f454de00c9193cc6/package/kedro_viz/data_access/repositories/catalog.py#L103-L104, https://github.com/kedro-org/kedro-viz/blob/fdcda72f13e406ed7a2cbac5f454de00c9193cc6/package/kedro_viz/data_access/repositories/catalog.py#L128-L131
- kedro-mlflow uses `DataCatalog._datasets` https://github.com/Galileo-Galilei/kedro-mlflow/blob/dc3b7bf98a50f1dc5048b85e42a2620bde1de466/kedro_mlflow/framework/hooks/mlflow_hook.py#L156

This was already discussed in Tech Design on October 2022 https://github.com/kedro-org/kedro/issues/1778#issuecomment-1292054256

> The reason why it's not straightforward to fetch datasets from the catalog directly, is because the catalog was designed to hide the dataset details and implementation. It's meant for loading and saving the data, but not modify in any way. 

There's a possibility that this is preventing Kedro Viz from fully supporting dataset factories for their experiment tracking functionality https://github.com/kedro-org/kedro-viz/issues/1480.

## Research questions

We would like to understand (TBC):

- Why do users need to access datasets from the catalog directly? (verbatim from [@merelcht's comment above](https://github.com/kedro-org/kedro/issues/1978#issue-1424020750))
- Why does the current "frozen" `.catalog` property not serve users who resort to private APIs instead?

**Comment by astrojuanlu** [comment] 2024-02-23 11:23
One more evidence point:

- Vizro uses `DataCatalog._get_dataset` https://github.com/mckinsey/vizro/blob/7b4131ccd31c46c9012caebdbb0721a1bcb48bc0/vizro-core/src/vizro/integrations/kedro/_data_manager.py#L23-L24

**Comment by astrojuanlu** [comment] 2024-02-23 16:15
And another one:

- v6d https://github.com/v6d-io/v6d/blob/9a15b3760671c82a157349c41538d9be5c631ad8/python/vineyard/contrib/kedro/plugins/hook.py#L47-L54

**Comment by iamelijahko** [comment] 2024-06-03 18:02
### Why are we doing this research?

The DataCatalog API, an older Kedro component, needs a refactor to better align with user needs. GitHub threads reveal confusion with the current API and its io.core and io.data_catalog workings, suggesting a general rethink is necessary.

This research aims to reimagine the DataCatalog as a flexible, intuitive tool for managing datasets, addressing the limitations of the current "frozen" datasets view, and reducing reliance on undocumented private APIs.

**Comment by astrojuanlu** [comment] 2024-06-06 11:03
@iamelijahko opened a new summary ticket here #3934 so we have fulfilled the original intent of understanding "What are the user needs for the catalog API". Closing this one!

**Closed by astrojuanlu** 2024-06-06 11:03 UTC
Labels: Stage: User Research :microscope:
