### ISSUE TITLE
Create a 'Best practices' documentation page under 'Get started'

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro#1898] opened 2022-10-04 17:45 UTC
## Description
It would be good to have a new docs page under 'Get Started' that briefly introduces the reader to linting and testing. It should then point them to our new docs pages that are being written as a response to the tickets:

- [#1619](https://github.com/kedro-org/kedro/issues/1619)
- [#1620](https://github.com/kedro-org/kedro/issues/1620)

## Context
This is an important step in deprecating `kedro test` and `kedro lint`. It gives more visibility to our new documentation, which is being written as an alternative to these commands.

**Comment by stichbury** [comment] 2022-10-17 09:41
I'm not convinced that Get Started is the place for lint/test information as it's probably not the first thing a new user looks to do. We certainly need a section, but the location may need some further consideration.

**Comment by stichbury** [comment] 2022-11-15 11:23
I have tentatively added a section on best practice in Kedro projects to a "Kedro project setup" section in a newly reorganised docs ([visible here](https://stichbury.github.io/)). So this could potentially happen within the basis of that work (covered by #1989)

**Comment by stichbury** [comment] 2022-11-15 11:30
Also take a look at https://github.com/kedro-org/kedro/issues/1271 as a somewhat related issue

**Comment by stichbury** [comment] 2023-07-05 16:41
This is a duplicate of https://github.com/kedro-org/kedro-devrel/issues/80

**Closed by stichbury** 2023-07-05 16:41 UTC
Labels: Component: Documentation 📄, Issue: Feature Request
